name: 'Pipeline 04/07'
on:  #formato da nossa pipeline, trigger, o que aciona
  # Habilita botão na interface web para acionar manualmente a pipeline
  
  pull_request: #adicionar essa opção executa automatico no push sem rpecisar clicar no botão
    branches: 
      - main
  workflow_dispatch:

## Nossos Jobs, etapas

jobs:
  integracao:
    name: 'Integração' #nome que aparece na interface grafica
    runs-on: ubuntu-latest # qual S.O quer que excute, gitlab vai proporcionar esse sistema
    steps: 
        # equivalente ao git clone - 1 etapa
      - uses: actions/checkout@v4 
      - name: 'Instalação de dependencias'
        run: pip install -r requirements.txt
      - name: 'Testes unitários'
        run: pytest
      - name: 'Cobertura de código'
        run: pytest --cov --cov-fail-under=80
      - name: 'Análise estática'
        run: bandit -r app/
      - name: 'Linting'
        run: pylint app/ || true
  fossa:
    needs: integracao
    name: 'Análise de dependências e conformidade'
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: 'FOSSA'
        uses: fossas/fossa-actions@main
        with:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}

  entrega:
    needs: [integracao, fossa]
    name: 'Entrega'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Autenticação"
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Configurando QEMU"
        uses: docker/setup-qemu-action@v3
      - name: "Configurando buildx"
        uses: docker/setup-buildx-action@v3
      - name: "Build e push"
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/curso-devops:latest

  implantacao:
    runs-on: self-hosted
    needs: entrega
    name: "Implantacao"
    steps:
      - uses: actions/checkout@v4
      - name: 'Aplicacao do manifesto'
        run: kubectl delete -f deployment.yaml && kubectl apply -f deployment.yaml